import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Sidebar from './components/Sidebar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`flex max-h-screen ${inter.className}`}>
        <Sidebar />
        <div className='flex shrink-0 grow flex-col'>
          <Navbar />
          <main className='m-4 grow'>{children}</main>
        </div>
      </body>
    </html>
  );
}
