definitions:
  controllers.GetUsers.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  models.EditUserRequest:
    properties:
      id:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - id
    - role
    - username
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.OkResponse:
    properties:
      message:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      password:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - password
    - role
    - username
    type: object
  models.Role:
    properties:
      id:
        type: string
      role:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/create-user:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/models.OkResponse'
        "400":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create new user
      tags:
      - Users
  /users/delete-user/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User Id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OkResponse'
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Deletes the user
      tags:
      - Users
  /users/edit-user:
    put:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.EditUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OkResponse'
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Edit a user's info
      tags:
      - Users
  /users/get-users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/controllers.GetUsers.User'
              type: array
            type: array
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all users
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OkResponse'
        "400":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Login the user
      tags:
      - Users
  /users/logout:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OkResponse'
        "400":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Logout current session
      tags:
      - Users
  /users/roles:
    get:
      consumes:
      - application/json
      parameters:
      - description: ApiKey header
        in: header
        name: x-api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/models.Role'
              type: array
            type: array
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Return the roles available
      tags:
      - Users
  /users/user-data:
    get:
      consumes:
      - application/json
      parameters:
      - description: ApiKey header
        in: header
        name: x-api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: ' '
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Gets data of current user
      tags:
      - Users
swagger: "2.0"
